<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Consider the four matrices, (20 points each)

In [30]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

print("A) AB")
print(np.dot(A,B))

print("\nB) D+D")
print(np.add(D,D))

print("\nC) 2C")
print(np.multiply(2,C))

A) AB
[[22 28]
 [49 64]]

B) D+D
[[2 4]
 [6 8]]

C) 2C
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2. Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python program . (40 points)

In [35]:
A = np.array([2,7,4])
B = np.array([3,9,8])

sol = [(A[1]*B[2])-(A[2]*B[1]), (A[2]*B[0])-(A[0]*B[2]), (A[0]*B[1])-(A[1]*B[0])]

print(sol)
print(np.cross(A,B))

[20, -4, -3]
[20 -4 -3]
