<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Algebra

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([[1,4],
              [0,3]])

round(np.linalg.det(A))

3

In [ ]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

import numpy as np

B = np.array([[1,3,5,6],
              [0,3,1,3],
              [3,1,8,2],
              [5,2,6,8]])
round(np.linalg.det(B))

-235

Coding Activity 9

In [ ]:
A = np.array([[1,2,3],[3,2,1],[2,3,1]])
B = np.array([[4,5,6],[6,5,4],[5,6,4]])
C = np.array([[7,8,9],[9,8,7],[8,9,7]])

print("Matrices:")
print(A, "\n")
print(B, "\n")
print(C, "\n")

Matrices:
[[1 2 3]
 [3 2 1]
 [2 3 1]] 

[[4 5 6]
 [6 5 4]
 [5 6 4]] 

[[7 8 9]
 [9 8 7]
 [8 9 7]] 



In [ ]:
#Associative Property
print("Associative Property: (AB)C = A(BC)")

AB = np.dot(A,B)
AB_C = np.dot(AB,C)

print("\n(AB)C =\n", AB_C)


BC = np.dot(B,C)
A_BC = np.dot(A,BC)

print("\nA(BC) =\n", A_BC)

Associative Property: (AB)C = A(BC)

(AB)C =
 [[722 746 692]
 [722 750 688]
 [720 748 692]]

A(BC) =
 [[722 746 692]
 [722 750 688]
 [720 748 692]]


In [ ]:
#Distributive Property
print("Distributive Property: A(B+C) = AB + AC")

BplusC = np.add(B,C)
A_BplusC = np.dot(A,BplusC)

print("\nA(B+C) =\n", A_BplusC)


AB = np.dot(A,B)
AC = np.dot(A,C)

ABplusAC = np.add(AB,AC)

print("\nAB + AC =\n", ABplusAC)

Distributive Property: A(B+C) = AB + AC

A(B+C) =
 [[80 84 70]
 [76 80 78]
 [80 80 74]]

AB + AC =
 [[80 84 70]
 [76 80 78]
 [80 80 74]]


In [ ]:
#Closure Property
print("Closure Property: size of A = size of dA")

d = 3
dA = np.dot(d, A)

print("\nd =", d)
print("\nA =\n", A)
print("\ndA =\n", dA)

Closure Property: size of A = size of dA

d = 3

A =
 [[1 2 3]
 [3 2 1]
 [2 3 1]]

dA =
 [[3 6 9]
 [9 6 3]
 [6 9 3]]


In [ ]:
#Multiplicative Identity Property
print("Multiplicative Identity Property: if A is an n * n matrix and I is an identity matrix of order n then AI = A")

I = np.eye(3,3)
AI = np.dot(A,I)

print("\nI =\n", I)
print("\nA =\n", A)
print("\nA =\n", AI)

Multiplicative Identity Property: if A is an n * n matrix and I is an identity matrix of order n then AI = A

I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A =
 [[1 2 3]
 [3 2 1]
 [2 3 1]]

A =
 [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]


In [ ]:
#Multiplicative property of Zero
print("Multiplicative property of Zero: If a matrix is multiplied by a zero matrix then the resultant matrix is a zero matrix.")

ZeroM = np.zeros([3,3])
AxZero = np.dot(A,ZeroM)

print("\nZero Matrix =\n", ZeroM)
print("\nA =\n", A)
print("\nA * Zero Matrix =\n", AxZero)

Multiplicative property of Zero: If a matrix is multiplied by a zero matrix then the resultant matrix is a zero matrix.

Zero Matrix =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A =
 [[1 2 3]
 [3 2 1]
 [2 3 1]]

A * Zero Matrix =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Commutative Property
print("Commutative Property: AB ≠ BA")

AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =\n", AB)
print("\nBA =\n", BA)
print("\nNot Equal!")

Commutative Property: AB ≠ BA

AB =
 [[31 33 26]
 [29 31 30]
 [31 31 28]]

BA =
 [[31 36 23]
 [29 34 27]
 [31 34 25]]

Not Equal!
