<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations

Vector Addition

In [12]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])
print(A+B+C)

print(np.add(A, np.add(B,C)))
print(np.sum(B))

[ 4  3 -1]
[ 4  3 -1]
2



Vector Subtraction

In [13]:
np.subtract(A,B)
A-B

array([-2,  1,  2])

Vector Multiplication

In [14]:
np.multiply(A,B)
A*B

array([3, 2, 0])

Vector Division

In [15]:
np.divide(A,B)
print(A/B)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
print(C//D)

print(np.array(A/B,dtype=int))

[ 0.33333333  2.         -0.        ]
[3. 1. 7.]
[0 2 0]
