<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System of Linear Equations

In [1]:
import numpy as np

X = np.array([[1,1,1],
              [3,-2,-1],
              [-1,4,2]],
              dtype=float)
Y = np.array([[1],
              [4],
              [-3]],
              dtype=float)

print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


Coding Activity 10

Let's say you have a bakery and you are purchasing supplies consisting of flour, yeast, and eggs from your supplier. For month 1 you bought a bakery promo that consists of 30 sacks of flour, 10 packs of yeast, and 120 eggs and you are charged for 12,500 pesos. For month two you bought a different bakery promo that consists of 40 sacks of flour, 20 packs of yeast, and 200 eggs then you are charged with 18,000 pesos. And then for month three you bought yet a different bakery promo that consists of 50 sacks of flour, 40 packs of yeast, and 360 eggs for 25,700 pesos. Now you are wondering if the promos are more cost-effective compared to buying them as a regular buyer, what could be the price of the flour per sack, yeast per pack, and one piece of egg?

In [29]:
import numpy as np
#x = flour
#y = yeast
#z = eggs

#month1 => 30x + 10y + 120z = 12500
#month2 => 40x + 20y + 200z = 18000
#month3 => 50x + 40y + 360z = 25700

month = np.array([[30, 10, 120],
                  [40, 20, 200],
                  [50, 40, 360]])
price = np.array([[12500],
                  [18000],
                  [25700]])

sol = np.linalg.solve(month, price)
flour_sol, yeast_sol, eggs_sol = sol[:, 0]

print("Price of flour: ₱", round(flour_sol))
print("Price of yeast: ₱", round(yeast_sol))
print("Price of eggs:  ₱", round(eggs_sol))

Price of flour: ₱ 330
Price of yeast: ₱ 140
Price of eggs:  ₱ 10
