<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Special_Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Special Prelim Exam

Question 1. (20 points) Create a Multiplication Table/Chart of 10 (10x10) using numpy/ python program.

In [60]:
import numpy as np

for col in range(1,11):
  for row in range(1,11):
    table = np.array([col*row])
    print(table, end="\t")
  print("")

[1]	[2]	[3]	[4]	[5]	[6]	[7]	[8]	[9]	[10]	
[2]	[4]	[6]	[8]	[10]	[12]	[14]	[16]	[18]	[20]	
[3]	[6]	[9]	[12]	[15]	[18]	[21]	[24]	[27]	[30]	
[4]	[8]	[12]	[16]	[20]	[24]	[28]	[32]	[36]	[40]	
[5]	[10]	[15]	[20]	[25]	[30]	[35]	[40]	[45]	[50]	
[6]	[12]	[18]	[24]	[30]	[36]	[42]	[48]	[54]	[60]	
[7]	[14]	[21]	[28]	[35]	[42]	[49]	[56]	[63]	[70]	
[8]	[16]	[24]	[32]	[40]	[48]	[56]	[64]	[72]	[80]	
[9]	[18]	[27]	[36]	[45]	[54]	[63]	[72]	[81]	[90]	
[10]	[20]	[30]	[40]	[50]	[60]	[70]	[80]	[90]	[100]	


Question 2. (10 points) In relation to Question 1, show a solution that triples all the values of each element.

In [61]:
import numpy as np

for col in range(1,11):
  for row in range(1,11):
    table = np.array([3*col*row])
    print(table, end="\t")
  print("")

[3]	[6]	[9]	[12]	[15]	[18]	[21]	[24]	[27]	[30]	
[6]	[12]	[18]	[24]	[30]	[36]	[42]	[48]	[54]	[60]	
[9]	[18]	[27]	[36]	[45]	[54]	[63]	[72]	[81]	[90]	
[12]	[24]	[36]	[48]	[60]	[72]	[84]	[96]	[108]	[120]	
[15]	[30]	[45]	[60]	[75]	[90]	[105]	[120]	[135]	[150]	
[18]	[36]	[54]	[72]	[90]	[108]	[126]	[144]	[162]	[180]	
[21]	[42]	[63]	[84]	[105]	[126]	[147]	[168]	[189]	[210]	
[24]	[48]	[72]	[96]	[120]	[144]	[168]	[192]	[216]	[240]	
[27]	[54]	[81]	[108]	[135]	[162]	[189]	[216]	[243]	[270]	
[30]	[60]	[90]	[120]	[150]	[180]	[210]	[240]	[270]	[300]	


Question 3. (10 points) Create a square matrix that has a diagonal of 5's.

In [62]:
sqr = np.array([[5,0,0,0,0],
                [0,5,0,0,0],
                [0,0,5,0,0],
                [0,0,0,5,0],
                [0,0,0,0,5]])
print(sqr)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


Question 4. (30 points) Create a matrix whose elements are:
Type a python program that can view the size, shape, and dimension of the matrix above.

In [66]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

size = np.size(matrix)
shape = np.shape(matrix)
dim = np.ndim(matrix)

print("The size of the matrix is", size)
print("The shape of the matrix is",shape)
print("The number of dimensions of the matrix is",dim)

The size of the matrix is 12
The shape of the matrix is (3, 4)
The number of dimensions of the matrix is 2


Question 5. (30 points) Create a result array by subtracting the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [68]:
arrayOne = np.array([[5,6,9], [21,18,27]])
arrayTwo = np.array([[15,33,24], [4,7,1]])

diff = np.subtract(arrayOne, arrayTwo)
print(diff)

print("")
sqr_elm = diff**2
print(sqr_elm)

[[-10 -27 -15]
 [ 17  11  26]]

[[100 729 225]
 [289 121 676]]
