<a href="https://colab.research.google.com/github/EminImura/58013-Linear-Algebra/blob/main/Vectors%2C_Spaces%2C_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vectors

In [19]:
import numpy as np
a = np.array([4,3])
b = np.array([2,-5])
print('Vector A is', a)
print('Vector B is', b)

Vector A is [4 3]
Vector B is [ 2 -5]
[  8 -15]


In [54]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)

ballss = np.shape(ball1) + np.shape(ball2)
print(ballss)

x = np.ndim(ball1)
print(x)

[1 2 3]
[ 0  1 -1]
(3, 3)
1


Spaces and Operation (Addition)

In [68]:
import numpy as np
R = np.array([[6],[2]])

a = np.array([4,3])
b = np.array([2,-5])
r1 = a+b
r2 = np.add(a,b)

print(r1)
print(r2)

[ 6 -2]
[ 6 -2]


Subtraction

In [69]:
a = np.array([4,3])
b = np.array([2,-5])
r1 = a-b
r2 = np.subtract(a,b)

print(r1)
print(r2)

[2 8]
[2 8]


Multiplication

In [86]:
a = np.array([4,3])
b = np.array([2])
print(a*b)

a1 = np.array([4,3])
b1= np.array([[2],[-5]])
print(np.multiply(a1, b1))

[8 6]
[[  8   6]
 [-20 -15]]


Dot Product

In [85]:
a1 = np.array([4,3])
b1= np.array([[2],[-5]])
print(np.dot(a1, b1))

[-7]


Cross Product

In [83]:
a1 = np.array([4,3])
b1= np.array([2,-5])
print(np.cross(a1, b1))

-26


Property of Matrix

In [100]:
#identity matrix
c = np.eye(3,3)
print(c)

#zero matrix
d = np.zeros([5,5])
print(d)

#full matrix
e = np.full((3,3),7)
print(e)

#transpose of matrix
f = np.transpose(np.multiply(a1, b1))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
